### ISSUE TITLE
Hi @raotaohub, 感谢提交这个功能！

### ISSUE THREAD

**Issue by raotaohub** [SevenOutman/aplayer-react#18]
Hi @raotaohub, 感谢提交这个功能！

不过，从当前实现的结果来看，在拖动过程中音频立即跟随拖动调整播放进度，会给拖拽交互带来一些问题：

1. 连续拖动时出现杂音
2. 如果在松开鼠标前音频已经播放了一会，松开鼠标时音频进度会跳回鼠标所在的位置

录屏演示如下

https://github.com/SevenOutman/aplayer-react/assets/8225666/95d60357-2900-4db3-b138-7a43dfd49455

我希望这两个问题可以被解决。
作为参考，网易云音乐客户端的拖动进度交互效果如下

https://github.com/SevenOutman/aplayer-react/assets/8225666/f24e8f2d-4548-4c1e-ae7d-03d015591452

_Originally posted by @SevenOutman in https://github.com/SevenOutman/aplayer-react/pull/17#pullrequestreview-1429689427_

**Comment by SevenOutman** [comment]
Closed and locked as it was accidentally opened (see https://github.com/SevenOutman/aplayer-react/pull/17#issuecomment-1550819579).
